# Generated by Django 4.1.1 on 2023-01-25 16:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
