# Generated by Django 3.2.6 on 2023-02-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_alter_ticket_screenshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('reported', 'Reported'), ('todo', 'Todo'), ('in_progress', 'In Progress'), ('done', 'Done'), ('blocked', 'Blocked')], default='reported', max_length=255),
        ),
    ]
